<?xml version="1.0"?>
<package format="3">
  <name>pkg08_parameters_cpp</name>
  <version>0.1.0</version>
  <description>ROS2 Tutorial - Node Parameters in C++</description>
  <maintainer email="darmawandeveloper@gmail.com">agus-darmawan</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
